### ISSUE TITLE
Adding a description or comment property to devspace commands in yaml configuration

### ISSUE THREAD

**Issue by cedricmckinnie** [devspace-cloud/devspace#1115]
**Is your feature request related to a problem?**  
No, this is a potential enhancement

**Which solution do you suggest?**  
Simple example usage in devspace.yaml:

commands:
- name: install
  command: npm install
  description: "Run this to download node dependencies specified in package.json into the node_modules folder."
- name: build
  command: devspace build
  description: "Run this to build nginx docker image"

It would be useful to display this in the devspace UI for new developers and self-documentation of devspace commands.

This would also need to be updated in "devspace list commands" output.

**Task List**  

- [ ] add 'name' and 'description' optional properties to yaml config
- [ ] add 'name' and 'description' to devspace UI
- [ ] add name and description to 'devspace list' command

/kind feature

**Comment by FabianKramm** [comment]
@cedricmckinnie thanks for opening this issue! Sounds like a good idea, we can add this as an optional property!

**Comment by cedricmckinnie** [comment]
@FabianKramm Thanks for the prompt response! Come to think of it, it might also be a good idea to include an optional "name" property as well to be displayed in the UI. Will add a checklist to ticket description just so we have a consolidated list of desired items for this ticket.

**Comment by LukasGentele** [comment]
Implemented as part of [v4.13](https://github.com/devspace-cloud/devspace/releases/tag/v4.13.0)
